---
title: Progteins and processors documentation
---

The 'Progteins' forlder documents the progteins, and the  'Processors' folder documents the processors.
This page summarizes both of them.

# General summary

-100- : genetic data
-1 : phenotypic body end
0-99 : core functions
100-199 : general genesis functions
200-299 : metabolic functions : internal utility functions
300-399 : behavioral functions : external utility functions
400-499 : machine learning functions

# Detailed summary

Progteins are denoted with (p)

## Core units

* 0 : meta-exec progtein (p)
* 1 : main function
* 2 : core switcher

## Genesis units

* 103 : free molecules picker wrapper
* 104 : self-compilation func ID list (p)
* 105 : meta-sequential transcriber
* 106 : mRNA meta-aggregator

### tRNAs

* 9999 : tRNA_RET
* 10000 : tRNA_CVARS
* 10001 : tRNA_IVARS
* 10100 : tRNA_SLVcst
* 10101 : tRNA_SDLVcst
* 10110 : tRNA_SLVLV
* 10111 : tRNA_SDLVLV
* 10112 : tRNA_SLVDLV
* 10113 : tRNA_SDLVDLV
* 10114 : tRNA_ScstLV
* 10115 : tRNA_SLVaddr
* 10150 : tRNA_RGLVLV
* 10170 : tRNA_WGDLV
* 10200 : tRNA_GILV
* 10201 : tRNA_GDILV
* 10202 : tRNA_GIDLV
* 10203 : tRNA_GDIDLV
* 10210 : tRNA_GTSLV
* 10211 : tRNA_GTSLVD
* 10212 : tRNA_GTSDLV
* 10250 : tRNA_GLVO
* 10500 : tRNA_IF0
* 10600 : tRNA_SIJ
* 10700 : tRNA_SEJ
* 10800 : tRNA_SWJ
* 10900 : tRNA_JLV
* 11000 : tRNA_SOScst
* 11001 : tRNA_SOSLV
* 11010 : tRNA_GISLV
* 11100 : tRNA_PCSI
* 11150 : tRNA_PLVSI
* 11200 : tRNA_PCSWI
* 11250 : tRNA_PLVSWI
* 11300 : tRNA_CMPLVcst
* 11350 : tRNA_CMPLVLV
* 11400 : tRNA_OPEcstcst
* 11401 : tRNA_OPEcstLV
* 11402 : tRNA_OPELVcst
* 11403 : tRNA_OPELVLV
* 11450 : tRNA_INCcst
* 11451 : tRNA_INCLV
* 11452 : tRNA_INCDLV
* 11453 : tRNA_INCS
* 11500 : tRNA_CALLcst
* 11501 : tRNA_CALLLV
* 12000 : tRNA_GScstcst
* 12001 : tRNA_GScstLV
* 12002 : tRNA_GSLVcst
* 12003 : tRNA_GLVLV
* 13000 : tRNA_USLV
* 13001 : tRNA_RULV
* 13100 : tRNA_EMPTY
* 13200 : tRNA_WRITE
* 14999 : tRNA_HALT

*Meta tRNAs*
* 14000 : tRNA_MP
* 14010 : tRNA_ME
* 14100 : tRNA_Mcst
* 14101 : tRNA_M0
* 14102 : tRNA_M1
* 14103 : tRNA_M2
* 14104 : tRNA_M3
* 14201 : tRNA_MCPY
* 14300 : tRNA_Marg
* 14301 : tRNA_MargW
* 14310 : tRNA_MLV
* 14311 : tRNA_MLVW

*Special tRNAs*
* 15000 : tRNA_GPTR
* 15001 : tRNA_SP_FCTADD
* 15002 : tRNA_SP_GFPTRLV
* 15003 : tRNA_SP_GSPLV
* 15004 : tRNA_SP_GCPY

## Metabolic functions

* 200 : body size calc (p)
* 201 : new func writer (p)
* 206 : ribosome
* 207 : RNAP (p)
* 208 : transcriber

## Behavioral functions

* 300 : free molecules picker (p)
* 301 : find empty place
