#include "InstructionMapping.hpp"

std::map<instruction, std::string> instruction_str = {
    { instruction::XXX, "XXX" },
    { instruction::MOV, "MOV" },
    { instruction::CPY, "CPY" },
    { instruction::CPYIN, "CPYIN" },
    { instruction::CPYOUT, "CPYOUT" },
    { instruction::INC, "INC" },
    { instruction::DEC, "DEC" },
    { instruction::ADD, "ADD" },
    { instruction::SUB, "SUB" },
    { instruction::MUL, "MUL" },
    { instruction::DIV, "DIV" },
    { instruction::OPP, "OPP" },
    { instruction::CMP, "CMP" },
    { instruction::JMP, "JMP" },
    { instruction::JMP, "CPYIS" },
    { instruction::JMP, "SETOS" },
    { instruction::JRA, "JRA" },
    { instruction::JRS, "JRS" },
    { instruction::JE, "JE" },
    { instruction::JL, "JL" },
    { instruction::JG, "JG" },
    { instruction::JLE, "JLE" },
    { instruction::JGE, "JGE" },
    { instruction::JRE, "JRE" },
    { instruction::JRE, "JE" },
    { instruction::JRL, "JL" },
    { instruction::JRG, "JG" },
    { instruction::JRLE, "JLE" },
    { instruction::JRGE, "JGE" },
    { instruction::HALT, "HALT" },
    { instruction::RUD, "RUD" },
    { instruction::RUI, "RUI" },
    { instruction::RN, "RN" },
    { instruction::GR, "GR" },
    { instruction::GINS, "GINS" },
    { instruction::GDEL, "GDEL" },
    { instruction::GDELW, "GDELW" },
    { instruction::GSET, "GSET" },
    { instruction::GADD, "GADD" },
    { instruction::GCPY, "GCPY"},
    { instruction::MARKER, "MARKER"},
    { instruction::GCPYM, "GCPYM"}
};