---
title: Documentation of the RNAP
output: 
  html_document:
    code_folding: hide
---


# General info

Goal : transcribing a gene into mRNA

Input : func ID
Output : mRNA of the corresponding func (with additional info) on the stack



## Description

This progtein finds the wanted gene in DNA and writes it in data as mRNA.

### First part : DNA start

Loop in molecular body, and stop when current pos is a molecular marker.
If the ID two places after the marker is -1, exit loop : DNA has been found.
 
### Second part : gene start

Get func ID from stack, and loop through DNA to find corresponding gene :
stop when a GSTART_ID is found, and if next nucleotide is wanted func ID, exit loop.

### Third part : DNA to mRNA

Get stack ptr from stack (called RNA ptr) and leave room to put info for ribosome.
Loop through the gene and write nucleotides at RNA ptr (incrementing it also).
Stop transcription when a GSTOP_ID is found.

### Fourth part : post-process

Write RNA ptr (i.e. end of RNA) on top of stack, leave room for ribosome and write func ID on top of stack.

# Variables

var 1 : loop var
var 2 : val in body at loop var, then RNA loop var
var 3 : condition var
var 4 : TOPS val : func ID 
var 5 : inner condition var (in while loop)
var 6 : GSTART_ID & GSTOP_ID


# Pseudo-code

```{pseudo class.source='foldable'}

*Find DNA in body*
while val in body is DNA start (-1 after molecular marker)
  increase loop var by 7
  get val in body at loop var
  if this val is a marker:
    look at val in body 2 places after current pos
    update condition : this val is != -1

*DNA found, loop var is now looping through DNA and not molecular body*

*Find gene coding func (loop till GSTART_ID)*
Get func ID from stack
while val in body is not the func ID after a gene start
  increment loop var
  get val in body at loop var
  if this val is a gene start (GSTART_ID)
    look at val in body next to current pos
    update condition : this val is != func ID

Increment stack ptr and get stack ptr into new ptr var (called RNA ptr)
Set to 0 the two positions after RNA ptr (for later use : ribosome ptr and func ID)

*Get gene from DNA to mRNA (loop till GSTOP_ID)*
While loop var is not a gene stop
  increment loop var and RNA ptr
  get val at loop var, i.e. nucleotide val
  write nucleotide on RNA ptr
  update condition : nucleotide is not a gene stop

Decrement RNA ptr (fencepost with while loop)
Put RNA ptr on TOPS (i.e. end of mRNA)
Decrease stack ptr by 2
Put func ID on TOPS
```

# Code

## DNA code

### Raw code

```{DNA class.source='foldable'}
GSTART_ID, 207, id_tRNA_CVARS, LV_place, 6, id_tRNA_IVARS, id_tRNA_SLVcst,
1, -7, id_tRNA_SLVcst, 3, 1, id_tRNA_IF0, 3, 
id_tRNA_OPELVcst, 0, 1, 7, id_tRNA_RGLVLV, 2, 1, 
id_tRNA_CMPLVcst, 0, 2, instruction::MARKER, 4, id_tRNA_IF0, 4, 
id_tRNA_OPELVcst, 0, 1, 2, id_tRNA_RGLVLV, 2, 1, 
id_tRNA_CMPLVcst, 0, 2, -1, 3, id_tRNA_INCLV, 1, 
3, id_tRNA_OPELVcst, 1, 1, 2, id_tRNA_SIJ, id_tRNA_SEJ, 
id_tRNA_SWJ, id_tRNA_SLVcst, 6, GSTART_ID-1, id_tRNA_INCLV, 0, 6, 
id_tRNA_GTSLV, 4, id_tRNA_SLVcst, 3, 1, id_tRNA_IF0, 3, 
id_tRNA_OPELVcst, 0, 1, 7, id_tRNA_RGLVLV, 2, 1,  
id_tRNA_CMPLVLV, 0, 6, 2, 5, id_tRNA_IF0, 5, 
id_tRNA_INCLV, 0, 1, id_tRNA_RGLVLV, 2, 1, id_tRNA_CMPLVLV, 
0, 2, 4, 3, id_tRNA_INCLV, 1, 3, 
id_tRNA_INCLV, 1, 1, id_tRNA_SIJ, id_tRNA_SEJ, id_tRNA_SWJ, id_tRNA_INCcst, 
0, 99, id_tRNA_SP_GSPLV, 2, id_tRNA_INCLV, 0, 2, 
id_tRNA_SDLVcst, 2, 0, id_tRNA_INCLV, 0, 2, id_tRNA_SDLVcst, 
2, 0, id_tRNA_INCLV, 0, 1, id_tRNA_SLVcst, 6, 
GSTOP_ID-1, id_tRNA_INCLV, 0, 6, id_tRNA_SLVcst, 3, 1, 
id_tRNA_IF0, 3, id_tRNA_INCLV, 0, 1, id_tRNA_INCLV, 0, 
2, id_tRNA_RGLVLV, 5, 1, id_tRNA_SDLVLV, 2, 5, 
id_tRNA_SLVDLV, 3, 2, id_tRNA_CMPLVLV, 0, 3, 6, 
3, id_tRNA_INCLV, 1, 3, id_tRNA_SWJ, id_tRNA_INCLV, 1, 
2, id_tRNA_PLVSWI, 2, id_tRNA_INCcst, 1, 99, id_tRNA_INCcst, 
1, 99, id_tRNA_PLVSWI, 4, id_tRNA_RET, GSTOP_ID, 0, 
```




### Commented code

```{pseudoDNA class.source='foldable'}
*Find DNA in body*
id_tRNA_SLVcst, 1, -7             // var1 <- -7
id_tRNA_SLVcst, 3, 1              // var3 <- 1
id_tRNA_IF0, 3
| id_tRNA_OPELVcst, 0, 1, 7       // var1+=7
| id_tRNA_RGLVLV, 2, 1            // var2 <- body val at var1
| id_tRNA_CMPLVcst, 0, 2, instruction::MARKER, 4    // var4 <- var2==MARKER
| id_tRNA_IF0, 4
| | id_tRNA_OPELVcst, 0, 1, 2       // var1+=2
| | id_tRNA_RGLVLV, 2, 1            // var2 <- body val at var1
| | id_tRNA_CMPLVcst, 0, 2, -1, 3   // var3 <- var2==-1
| | id_tRNA_INCLV, 1, 3             // var3--
| | id_tRNA_OPELVcst, 1, 1, 2       // var1-=2
| id_tRNA_SIJ
| id_tRNA_SEJ
id_tRNA_SWJ

*Look for gene coding the func (using func ID from stack)*
id_tRNA_SLVcst, 6, GSTART_ID-1    // var6 <- GSTART_ID-1 (to avoid meta-ID capture)
id_tRNA_INCLV, 0, 6               // var6++
id_tRNA_GTSLV, 4                  // var4 <- TOPS (func ID)
id_tRNA_SLVcst, 3, 1              // var3 <- 1
id_tRNA_IF0, 3
| id_tRNA_OPELVcst, 0, 1, 7       // var1+=7
| id_tRNA_RGLVLV, 2, 1            // var2 <- body val at var1
| id_tRNA_CMPLVLV, 0, 6, 2, 5     // var5 <- var6==var2 (if we are at the beginning of a gene)
| id_tRNA_IF0, 5
| | id_tRNA_INCLV, 0, 1             // var1++
| | id_tRNA_RGLVLV, 2, 1            // var2 <- body val at var1
| | id_tRNA_CMPLVLV, 0, 2, 4, 3     // var3 <- var2==var4
| | id_tRNA_INCLV, 1, 3             // var3--
| | id_tRNA_INCLV, 1, 1             // var1--
| id_tRNA_SIJ
| id_tRNA_SEJ
id_tRNA_SWJ

*Leave room for ribosome*
id_tRNA_INCcst, 0, 99             // stack ptr++
id_tRNA_SP_GSPLV, 2               // var2 <- stack ptr (to write zeros after stack for ribosome)
id_tRNA_INCLV, 0, 2               // var2++
id_tRNA_SDLVcst, 2, 0             // *var2 <- 0
id_tRNA_INCLV, 0, 2               // var2++
id_tRNA_SDLVcst, 2, 0             // *var2 <- 0

*var 1 is loop var*
*Get gene from DNA to mRNA (loop till GSTOP_ID)*
id_tRNA_INCLV, 0, 1               // var1++ (fencepost with previous loop)
id_tRNA_SLVcst, 6, GSTOP_ID-1     // var6 <- GSTOP_ID-1
id_tRNA_INCLV, 0, 6               // var6++
id_tRNA_SLVcst, 3, 1              // var3 <- 1
id_tRNA_IF0, 3
| id_tRNA_INCLV, 0, 1             // var1++
| id_tRNA_INCLV, 0, 2             // var2++
| id_tRNA_RGLVLV, 5, 1            // var5 <- body val at var1
| id_tRNA_SDLVLV, 2, 5            // *var2 <- var5
| id_tRNA_SLVDLV, 3, 2            // var3 <- *var2
| id_tRNA_CMPLVLV, 0, 3, 6, 3     // var3 <- var3==var6 (if we are at the end of the gene)
| id_tRNA_INCLV, 1, 3             // var3--
id_tRNA_SWJ

id_tRNA_INCLV, 1, 2               // var2-- (decrease RNA ptr : fencepost with loop above)
id_tRNA_PLVSWI, 2                 // TOPS <- var2 (put on stack for ribosome)
id_tRNA_INCcst, 1, 99             // stack ptr--
id_tRNA_INCcst, 1, 99             // stack ptr--
id_tRNA_PLVSWI, 4                 // TOPS <- var4 (func ID)

id_tRNA_RET
```


## Teleonomical code

### XASM code

```{XASM class.source='foldable'}
instruction::MARKER, 0, 207, 0, 0, 0, 0,


instruction::CPY, 1, 0, 0, 110, -7, 0,
instruction::ADD, 1, 1, 0, 110, 110, 7,
instruction::GR, 1, 2, 0, 101, 110, 0,
instruction::JRE, 0, 1, 0, 2, 101, instruction::MARKER,
instruction::JRS, 0, 0, 0, 3, 0, 0,

instruction::ADD, 1, 1, 0, 110, 110, 2,
instruction::GR, 1, 2, 0, 101, 110, 0,
instruction::JRE, 0, 1, 0, 3, 101, -1,
instruction::SUB, 1, 1, 0, 110, 110, 2,
instruction::JRS, 0, 0, 0, 8, 0, 0,


instruction::CPY, 1, 2, 0, 100, 99, 0,
instruction::INC, 1, 0, 0, 110, 0, 0,
instruction::GR, 1, 2, 0, 101, 110, 0,
instruction::JRE, 0, 1, 0, 2, 101, GSTART_ID,
instruction::JRS, 0, 0, 0, 3, 0, 0,

instruction::INC, 1, 0, 0, 110, 0, 0,
instruction::GR, 1, 2, 0, 101, 110, 0,
instruction::JRE, 0, 1, 1, 3, 101, 100,
instruction::DEC, 1, 0, 0, 110, 0, 0,
instruction::JRS, 0, 0, 0, 8, 0, 0,


instruction::INC, 1, 0, 0, 99, 0, 0,
instruction::CPY, 1, 1, 0, 101, 99, 0,

instruction::INC, 1, 0, 0, 101, 0, 0,
instruction::CPY, 2, 0, 0, 101, 0, 0,
instruction::INC, 1, 0, 0, 101, 0, 0,
instruction::CPY, 2, 0, 0, 101, 0, 0,

instruction::INC, 1, 0, 0, 110, 0, 0,
instruction::INC, 1, 0, 0, 101, 0, 0,
instruction::GR, 2, 2, 0, 101, 110, 0,
instruction::JRE, 0, 2, 0, 2, 101, GSTOP_ID,
instruction::JRS, 0, 0, 0, 4, 0, 0,

instruction::DEC, 1, 0, 0, 101, 0, 0,
instruction::CPY, 2, 1, 0, 99, 101, 0,
instruction::SUB, 1, 1, 0, 99, 99, 2,
instruction::CPY, 2, 1, 0, 99, 100, 0,


instruction::JMP, 2, 0, 0, 0, 0, 0,

instruction::MARKER, 0, 207, 0, 0, 0, 0,
```

### Raw code

```{Raw class.source='foldable'}
46, 0, 207, 0, 0, 0, 0,
2, 1, 0, 0, 110, -7, 0,
7, 1, 1, 0, 110, 110, 7,
39, 1, 2, 0, 101, 110, 0,
27, 0, 1, 0, 2, 101, 46,
21, 0, 0, 0, 3, 0, 0,
7, 1, 1, 0, 110, 110, 2,
39, 1, 2, 0, 101, 110, 0,
27, 0, 1, 0, 3, 101, -1,
8, 1, 1, 0, 110, 110, 2,
21, 0, 0, 0, 8, 0, 0,
2, 1, 2, 0, 100, 99, 0,
5, 1, 0, 0, 110, 0, 0,
39, 1, 2, 0, 101, 110, 0,
27, 0, 1, 0, 2, 101, -51451,
21, 0, 0, 0, 3, 0, 0,
5, 1, 0, 0, 110, 0, 0,
39, 1, 2, 0, 101, 110, 0,
27, 0, 1, 1, 3, 101, 100,
6, 1, 0, 0, 110, 0, 0,
21, 0, 0, 0, 8, 0, 0,
5, 1, 0, 0, 99, 0, 0,
2, 1, 1, 0, 101, 99, 0,
5, 1, 0, 0, 101, 0, 0,
2, 2, 0, 0, 101, 0, 0,
5, 1, 0, 0, 101, 0, 0,
2, 2, 0, 0, 101, 0, 0,
5, 1, 0, 0, 110, 0, 0,
5, 1, 0, 0, 101, 0, 0,
39, 2, 2, 0, 101, 110, 0,
27, 0, 2, 0, 2, 101, -77142,
21, 0, 0, 0, 4, 0, 0,
6, 1, 0, 0, 101, 0, 0,
2, 2, 1, 0, 99, 101, 0,
8, 1, 1, 0, 99, 99, 2,
2, 2, 1, 0, 99, 100, 0,
19, 2, 0, 0, 0, 0, 0,
46, 0, 207, 0, 0, 0, 0,
```