---
title: Progteins documentation
---

This folder contains the documentation of progteins necessary for the basic working of the EvoX algo.

# General info

A progtein is an atomic teleonomical unit, in the sense that it does not call any other progtein.

# Teleonomical summary

## Core progteins

The 'Core' folder documents the progteins responsible for the day-to-day working of the individual, 
such as executing other progteins or organs, depending on the 'sensorial' input.

* 0 : meta-exec progtein

## Genesis progteins

The 'Genesis' folder documents the progteins necessary for the genesis of individuals.
This paragraph summarises them.

* 104 : self-compilation func ID list

### tRNA progteins

tRNA progteins ar a special case of genesis progteins

* 9999 : tRNA_RET
* 10000 : tRNA_CVARS
* 10001 : tRNA_IVARS
* 10100 : tRNA_SLVcst
* 10101 : tRNA_SDLVcst
* 10110 : tRNA_SLVLV
* 10111 : tRNA_SDLVLV
* 10112 : tRNA_SLVDLV
* 10113 : tRNA_SDLVDLV
* 10114 : tRNA_ScstLV
* 10115 : tRNA_SLVaddr
* 10150 : tRNA_RGLVLV
* 10170 : tRNA_WGDLV
* 10200 : tRNA_GILV
* 10201 : tRNA_GDILV
* 10202 : tRNA_GIDLV
* 10203 : tRNA_GDIDLV
* 10210 : tRNA_GTSLV
* 10211 : tRNA_GTSLVD
* 10212 : tRNA_GTSDLV
* 10250 : tRNA_GLVO
* 10500 : tRNA_IF0
* 10600 : tRNA_SIJ
* 10700 : tRNA_SEJ
* 10800 : tRNA_SWJ
* 10900 : tRNA_JLV
* 11000 : tRNA_SOScst
* 11001 : tRNA_SOSLV
* 11010 : tRNA_GISLV
* 11100 : tRNA_PCSI
* 11150 : tRNA_PLVSI
* 11200 : tRNA_PCSWI
* 11250 : tRNA_PLVSWI
* 11300 : tRNA_CMPLVcst
* 11350 : tRNA_CMPLVLV
* 11400 : tRNA_OPEcstcst
* 11401 : tRNA_OPEcstLV
* 11402 : tRNA_OPELVcst
* 11403 : tRNA_OPELVLV
* 11450 : tRNA_INCcst
* 11451 : tRNA_INCLV
* 11452 : tRNA_INCDLV
* 11453 : tRNA_INCS
* 11500 : tRNA_CALLcst
* 11501 : tRNA_CALLLV
* 12000 : tRNA_GScstcst
* 12001 : tRNA_GScstLV
* 12002 : tRNA_GSLVcst
* 12003 : tRNA_GLVLV
* 12500 : tRNA_GADD
* 13000 : tRNA_USLV
* 13001 : tRNA_RULV
* 13100 : tRNA_EMPTY
* 13200 : tRNA_WRITE
* 14999 : tRNA_HALT

*Meta tRNAs*
* 14000 : tRNA_MP
* 14010 : tRNA_ME
* 14100 : tRNA_Mcst
* 14101 : tRNA_M0
* 14102 : tRNA_M1
* 14103 : tRNA_M2
* 14104 : tRNA_M3
* 14201 : tRNA_MCPY
* 14300 : tRNA_Marg
* 14301 : tRNA_MargW
* 14310 : tRNA_MLV
* 14311 : tRNA_MLVW

*Special tRNAs*
* 15000 : tRNA_GPTR
* 15001 : tRNA_SP_FCTADD
* 15002 : tRNA_SP_GFPTRLV
* 15003 : tRNA_SP_GSPLV
* 15004 : tRNA_SP_GCPY

## Metabolic progteins

* 200 : body size calc
* 201 : new func writer
* 207 : RNAP

## Behavioral progteins

* 300 : free molecules picker
* 301 : find empty place
