---
title: Documentation of meta-sequential transcription processor
output: 
  html_document:
    code_folding: hide
---


# General info

Goal : transcribe to progtein and processors all funcs of the list built by the self-compilation func ID list builder

Input : nothing
Output : builds a list of teleonomical code when executed several times ; executed once it will transcribe 
    the code of the last progtein or processor ID on ID list

This function transcribes the RNAs one by one : 
It gets the last progtein ID of the list, transcribes it to a progtein, and decreases the func ID list size.

## Description

This processor is meta-sequential, i.e. the individual needs to call this processor several times 
for it to work properly.

More precisely, the first part is called as much as it should, after what the second part is 
executed automatically.

### First part : DNA transcription

The meta-sequential transcriber gets the last ID of the list and decreases its size, 
and then call the transcription process (RNAP + ribosome) to transcribe the DNA into functional code.
After the transcription process has ended, the meta-sequential transcriber shift the func code 
so that it is contiguous with previously transcribed code.
 
### Second part 

After all DNA functions have been transcribed, the meta-sequential transcriber writes the code 
and DNA into the output, and then dumps the output into an available place in the environment.

# Variables

var 1 : position to transcribe code
var 2 : ptr to end of transcribed code
var 3 : func size & end of ID list ptr
var 4 : stack ptr manip var
var 5 : last ID of ID list
var 6 : current pos in body of transcribed code to cpy to output
var 7 : are we at end of transcription code ?
var 8 : current pos in output to copy transcribed code
var 9 : cmp var
var 10 : condition var


# Pseudo-code

```{pseudo class.source='foldable'}
get begin of transcribed code
get end of transcribed code

If list size!=0:
    get end of list val
    store stack ptr in end of list pos
    store end of list val after end of list pos
    set stack ptr to end of list val
    CALL RNAP 
    CALL meta-aggregator
    CALL ribosome
    get back func ID for phenotypic marker
    decrease stack ptr to get old stack ptr
    increase stack ptr several times to get end of transcribed phenotypic body
    set stack ptr to old stack ptr
    decrease val at TOPS (i.e. list size)
    set x = pos after end of list
    write phenotypic marker (begin of func)
    set y = x + v where v is such that y is the first transcribed codon
    While y != end of transcribed phenotypic body
        data at x = data at y
    write phenotypic marker (end of func)
    update begin and end of transcribed code (under TOPS)
Else
    set output size to transcribed code size
    copy transcribed code to output
```

# Code

## DNA code

### Raw code

```{DNA class.source='foldable'}
GSTART_ID, 105, id_tRNA_CVARS, LV_place, 10, id_tRNA_IVARS, id_tRNA_OPEcstcst, 
0, 99, 2, id_tRNA_GTSLV, 1, id_tRNA_INCcst, 0, 
99, id_tRNA_GTSLV, 2, id_tRNA_INCcst, 0, 99, id_tRNA_GTSLV, 
3, id_tRNA_IF0, 3, id_tRNA_SLVaddr, 4, 99, id_tRNA_OPELVLV, 
0, 3, 4, id_tRNA_SLVDLV, 5, 3, id_tRNA_INCLV, 
0, 3, id_tRNA_SDLVLV, 2, 4, id_tRNA_ScstLV, 99, 
2, id_tRNA_PLVSI, 5, id_tRNA_PLVSI, 5, id_tRNA_CALLcst, 107, 
id_tRNA_CALLcst, 207, id_tRNA_CALLcst, 116, id_tRNA_CALLcst, 206, id_tRNA_GTSLV, 
3, id_tRNA_INCcst, 1, 99, id_tRNA_GTSLV, 4, id_tRNA_OPEcstcst, 
0, 99, 3, id_tRNA_GTSLV, 2, id_tRNA_INCLV, 0, 
2, id_tRNA_ScstLV, 99, 4, id_tRNA_INCS, 1, id_tRNA_INCcst, 
1, 99, id_tRNA_INCS, 1, id_tRNA_GTSLV, 1, id_tRNA_SDLVcst, 
1, instruction::MARKER, id_tRNA_INCLV, 0, 1, id_tRNA_SDLVcst, 1, 
0, id_tRNA_INCLV, 0, 1, id_tRNA_SDLVLV, 1, 3, 
id_tRNA_INCLV, 0, 1, id_tRNA_SDLVcst, 1, 0, id_tRNA_INCLV, 
0, 1, id_tRNA_SDLVcst, 1, 0, id_tRNA_INCLV, 0, 
1, id_tRNA_SDLVcst, 1, 0, id_tRNA_INCLV, 0, 1, 
id_tRNA_SDLVcst, 1, 0, id_tRNA_INCLV, 0, 1, id_tRNA_SLVLV, 
5, 1, id_tRNA_OPELVcst, 0, 5, 5, id_tRNA_CMPLVLV, 
0, 5, 2, 6, id_tRNA_INCLV, 1, 6, 
id_tRNA_IF0, 6, id_tRNA_SDLVDLV, 1, 5, id_tRNA_INCLV, 0, 
1, id_tRNA_INCLV, 0, 5, id_tRNA_CMPLVLV, 0, 5, 
2, 6, id_tRNA_INCLV, 1, 6, id_tRNA_SWJ, id_tRNA_SDLVcst, 
1, instruction::MARKER, id_tRNA_INCLV, 0, 1, id_tRNA_SDLVcst, 1, 
0, id_tRNA_INCLV, 0, 1, id_tRNA_SDLVLV, 1, 3, 
id_tRNA_INCLV, 0, 1, id_tRNA_SDLVcst, 1, 0, id_tRNA_INCLV, 
0, 1, id_tRNA_SDLVcst, 1, 0, id_tRNA_INCLV, 0, 
1, id_tRNA_SDLVcst, 1, 0, id_tRNA_INCLV, 0, 1, 
id_tRNA_SDLVcst, 1, 0, id_tRNA_INCLV, 0, 1, id_tRNA_SDLVcst, 
1, 0, id_tRNA_INCLV, 0, 1, id_tRNA_PLVSWI, 1, 
id_tRNA_OPEcstcst, 1, 99, 3, id_tRNA_SIJ, id_tRNA_CMPLVcst, 0, 
3, -1, 9, id_tRNA_IF0, 9, id_tRNA_RET, id_tRNA_SIJ, 
id_tRNA_SEJ, id_tRNA_PLVSI, 1, id_tRNA_PLVSI, 2, id_tRNA_CALLcst, 301, 
id_tRNA_GTSLVD, 10, id_tRNA_GTSLVD, 2, id_tRNA_GTSLVD, 1, id_tRNA_CMPLVcst, 
0, 10, -1, 9, id_tRNA_IF0, 9, id_tRNA_RET, 
id_tRNA_SIJ, id_tRNA_SEJ, id_tRNA_INCcst, 1, 99, id_tRNA_GTSLV, 2, 
id_tRNA_GTSLV, 7, id_tRNA_INCcst, 1, 99, id_tRNA_GTSLV, 1, 
id_tRNA_INCLV, 1, 1, id_tRNA_INCLV, 1, 2, id_tRNA_OPELVLV, 
1, 7, 1, id_tRNA_SLVcst, 3, -7, id_tRNA_SLVcst, 
9, 1, id_tRNA_IF0, 9, id_tRNA_OPELVcst, 0, 3, 
7, id_tRNA_RGLVLV, 5, 3, id_tRNA_CMPLVcst, 0, 5, 
instruction::MARKER, 6, id_tRNA_IF0, 6, id_tRNA_OPELVcst, 0, 3, 
2, id_tRNA_RGLVLV, 5, 3, id_tRNA_CMPLVcst, 0, 5, 
-1, 9, id_tRNA_INCLV, 1, 9, id_tRNA_OPELVcst, 1, 
3, 2, id_tRNA_SIJ, id_tRNA_SEJ, id_tRNA_SWJ, id_tRNA_SLVLV, 4, 
3, id_tRNA_SLVcst, 9, 1, id_tRNA_IF0, 9, id_tRNA_OPELVcst, 
0, 4, 7, id_tRNA_RGLVLV, 5, 4, id_tRNA_CMPLVcst, 
0, 5, instruction::MARKER, 6, id_tRNA_IF0, 6, id_tRNA_OPELVcst, 
0, 4, 2, id_tRNA_RGLVLV, 5, 4, id_tRNA_CMPLVcst, 
0, 5, -1, 9, id_tRNA_INCLV, 1, 9, 
id_tRNA_OPELVcst, 1, 4, 2, id_tRNA_SIJ, id_tRNA_SEJ, id_tRNA_SWJ, 
id_tRNA_OPELVcst, 0, 4, 6, id_tRNA_SLVLV, 8, 4, 
id_tRNA_OPELVLV, 1, 8, 3, id_tRNA_INCLV, 0, 8, 
id_tRNA_OPELVcst, 0, 7, 21, id_tRNA_OPELVLV, 0, 7, 
8, id_tRNA_SOSLV, 7, id_tRNA_SLVcst, 6, 0, id_tRNA_SLVcst, 
5, GGENESIS_ID, id_tRNA_GLVO, 6, 5, id_tRNA_OPELVcst, 0, 
6, 2, id_tRNA_SLVcst, 5, 3, id_tRNA_GLVO, 6, 
5, id_tRNA_INCLV, 0, 6, id_tRNA_GLVO, 6, 7, 
id_tRNA_INCLV, 0, 6, id_tRNA_SLVcst, 5, 150, id_tRNA_GLVO, 
6, 5, id_tRNA_INCLV, 0, 6, id_tRNA_SLVcst, 5, 
-1, id_tRNA_GLVO, 6, 5, id_tRNA_OPELVcst, 0, 6, 
3, id_tRNA_SLVcst, 5, 19, id_tRNA_GLVO, 6, 5, 
id_tRNA_OPELVcst, 0, 6, 4, id_tRNA_SLVcst, 5, 36, 
id_tRNA_GLVO, 6, 5, id_tRNA_OPELVcst, 0, 6, 3, 
id_tRNA_OPELVLV, 1, 7, 8, id_tRNA_OPELVcst, 1, 7, 
21, id_tRNA_SLVLV, 7, 1, id_tRNA_CMPLVLV, 0, 7, 
2, 5, id_tRNA_INCLV, 1, 5, id_tRNA_IF0, 5, 
id_tRNA_SLVDLV, 5, 7, id_tRNA_GLVO, 6, 5, id_tRNA_INCLV, 
0, 7, id_tRNA_INCLV, 0, 6, id_tRNA_CMPLVLV, 0, 
7, 2, 5, id_tRNA_INCLV, 1, 5, id_tRNA_SWJ, 
id_tRNA_SLVLV, 7, 3, id_tRNA_CMPLVLV, 0, 7, 4, 
5, id_tRNA_INCLV, 1, 5, id_tRNA_IF0, 5, id_tRNA_RGLVLV, 
5, 7, id_tRNA_GLVO, 6, 5, id_tRNA_INCLV, 0, 
7, id_tRNA_INCLV, 0, 6, id_tRNA_CMPLVLV, 0, 7, 
4, 5, id_tRNA_INCLV, 1, 5, id_tRNA_SWJ, id_tRNA_INCLV, 
0, 6, id_tRNA_SLVcst, 5, 46, id_tRNA_GLVO, 6, 
5, id_tRNA_INCLV, 0, 6, id_tRNA_SLVcst, 5, -1, 
id_tRNA_GLVO, 6, 5, id_tRNA_WRITE, 9, 10, id_tRNA_INCS, 
1, id_tRNA_RET, id_tRNA_SEJ, id_tRNA_RET, GSTOP_ID, 0, 0, 
```




### Commented code

```{pseudoDNA class.source='foldable'}
id_tRNA_OPEcstcst, 0, 99, 2         // stack ptr+=2 (to begin at right place and avoid overlap)
id_tRNA_GTSLV, 1                    // var 1 <- TOPS (get begin of transcription ptr)
id_tRNA_INCcst, 0, 99               // stack ptr++
id_tRNA_GTSLV, 2                    // var 2 <- TOPS (get end of transcription ptr)
id_tRNA_INCcst, 0, 99               // stack ptr++
id_tRNA_GTSLV, 3                    // var 3 <- TOPS (get func ID list size)

id_tRNA_IF0, 3                      // if var 3
| id_tRNA_SLVaddr, 4, 99            // var 4 <- stack ptr
| id_tRNA_OPELVLV, 0, 3, 4          // var 3+= var 4 (pointer to end of list)
| id_tRNA_SLVDLV, 5, 3              // var 5 <- *var 3 (last func ID)
| id_tRNA_INCLV, 0, 3               // var 3++
| id_tRNA_SDLVLV, 2, 4              // *var 2 <- var 4 (end of transcribed code = stack ptr)
| id_tRNA_ScstLV, 99, 2             // stack ptr <- var 2
| id_tRNA_PLVS, 5,                  // arg for RNAP
| id_tRNA_PLVS, 5,                  // arg for RNAP (same as prev line)
|
| id_tRNA_CALLcst, 107              // CALL meta-mutator
| id_tRNA_CALLcst, 207              // CALL RNAP
| id_tRNA_CALLcst, 106              // CALL meta-aggregator
| id_tRNA_CALLcst, 206              // CALL ribosome
|
| id_tRNA_GTSLV, 3                  // var 3 <- func ID
| id_tRNA_INCcst, 1, 99             // stack ptr-- (pos of stack before calling funcs)
| id_tRNA_GTSLV, 4                  // var 4 <- stack ptr before calls
| id_tRNA_OPEcstcst, 0, 99, 3       // stck ptr += 3 (ptr to end of transcribed molecules)
| id_tRNA_GTSLV, 2                  // var 2 <- end of transcribed molecules
| id_tRNA_INCLV, 0, 2               // var2++ (fencepost)
| id_tRNA_ScstLV, 99, 4             // stack ptr <- var 4
| id_tRNA_INCS, 1                   // decrease func ID list size
| id_tRNA_INCcst, 1, 99             // stack ptr-- (pos of first transcribed codon)
| id_tRNA_INCS, 1                   // update pos of first transcribed codon (1 func ID less)
| id_tRNA_GTSLV, 1                  // var 1 <- ptr to shift transcribed molecules
| id_tRNA_SDLVcst, 1, instruction::MARKER // phenotypic marker (begin)
| id_tRNA_INCLV, 0, 1
| id_tRNA_SDLVcst, 1, 0
| id_tRNA_INCLV, 0, 1
| id_tRNA_SDLVLV, 1, 3 
| id_tRNA_INCLV, 0, 1
| id_tRNA_SDLVcst, 1, 0
| id_tRNA_INCLV, 0, 1
| id_tRNA_SDLVcst, 1, 0
| id_tRNA_INCLV, 0, 1
| id_tRNA_SDLVcst, 1, 0
| id_tRNA_INCLV, 0, 1
| id_tRNA_SDLVcst, 1, 0
| id_tRNA_INCLV, 0, 1               // phenotypic marker (begin)
| id_tRNA_SLVLV, 5, 1               
| id_tRNA_OPELVcst, 0, 5, 5         // transcribed genes are shifted of 5 pos toward 0
| id_tRNA_CMPLVLV, 0, 5, 2, 6 
| id_tRNA_INCLV, 1, 6
| id_tRNA_IF0, 6                    // jmp if cpy ptr == end ptr 
| | id_tRNA_SDLVDLV, 1, 5           // shift data
| | id_tRNA_INCLV, 0, 1
| | id_tRNA_INCLV, 0, 5
| | id_tRNA_CMPLVLV, 0, 5, 2, 6 
| | id_tRNA_INCLV, 1, 6
| id_tRNA_SWJ
|
| id_tRNA_SDLVcst, 1, instruction::MARKER // phenotypic marker (end)
| id_tRNA_INCLV, 0, 1
| id_tRNA_SDLVcst, 1, 0
| id_tRNA_INCLV, 0, 1
| id_tRNA_SDLVLV, 1, 3 
| id_tRNA_INCLV, 0, 1
| id_tRNA_SDLVcst, 1, 0
| id_tRNA_INCLV, 0, 1
| id_tRNA_SDLVcst, 1, 0
| id_tRNA_INCLV, 0, 1
| id_tRNA_SDLVcst, 1, 0
| id_tRNA_INCLV, 0, 1
| id_tRNA_SDLVcst, 1, 0
| id_tRNA_INCLV, 0, 1
| id_tRNA_SDLVcst, 1, 0             // add one more for overwriting
| id_tRNA_INCLV, 0, 1               // phenotypic marker (end)
| id_tRNA_PLVSWI, 1                 // put end of transcribed code
| id_tRNA_OPEcstcst, 1, 99, 3       // stack ptr -= 3 (set prog ptr to val at begin)
|
id_tRNA_SIJ
| id_tRNA_CMPLVcst, 0, 3, -1, 9     // var9 <- var3==-1 ? (STOP if -1)
| id_tRNA_IF0, 9
| | id_tRNA_RET
| id_tRNA_SIJ
| id_tRNA_SEJ
|
| id_tRNA_PLVSI, 1                // stack_ptr++, TOPS <- var1
| id_tRNA_PLVSI, 2                // stack_ptr++, TOPS <- var2
| id_tRNA_CALLcst, 301            // stack ptr++, TOPS <- empty place
| id_tRNA_GTSLVD, 10              // var10 <- empty place (or -1)
| id_tRNA_GTSLVD, 2               // get back var2
| id_tRNA_GTSLVD, 1               // get back var1
| id_tRNA_CMPLVcst, 0, 10, -1, 9  // var9 <- var10==-1 ? (1 if place not found)
|
| id_tRNA_IF0, 9
| | id_tRNA_RET
| id_tRNA_SIJ
| id_tRNA_SEJ
| 
| id_tRNA_INCcst, 1, 99
| id_tRNA_GTSLV, 2                  // var2 <- TOPS (end of transcribed code)
| id_tRNA_GTSLV, 7                  // var7 <- TOPS
| id_tRNA_INCcst, 1, 99
| id_tRNA_GTSLV, 1                  // var1 <- TOPS (beginning of transcribed code + 1)
| id_tRNA_INCLV, 1, 1               // var1--
| id_tRNA_INCLV, 1, 2               // var2--
| id_tRNA_OPELVLV, 1, 7, 1          // var7 -= var1 (var 7 = transcribed code size)
| 
| *var1, var2 locate transcribed code, var7 is transcribed code size*
| 
| 
| *find DNA in body*
| id_tRNA_SLVcst, 3, -7             // var3 <- -7
| id_tRNA_SLVcst, 9, 1              // var9 <- 1
| id_tRNA_IF0, 9
| | id_tRNA_OPELVcst, 0, 3, 7       // var3+=7
| | id_tRNA_RGLVLV, 5, 3            // var5 <- body val at var3
| | id_tRNA_CMPLVcst, 0, 5, instruction::MARKER, 6    // var6 <- var5==MARKER
| | id_tRNA_IF0, 6
| | | id_tRNA_OPELVcst, 0, 3, 2       // var3+=2
| | | id_tRNA_RGLVLV, 5, 3            // var5 <- body val at var3
| | | id_tRNA_CMPLVcst, 0, 5, -1, 9   // var9 <- var5==-1
| | | id_tRNA_INCLV, 1, 9             // var9--
| | | id_tRNA_OPELVcst, 1, 3, 2       // var3-=2
| | id_tRNA_SIJ
| | id_tRNA_SEJ
| id_tRNA_SWJ
| 
| *Look for end of DNA
| id_tRNA_SLVLV, 4, 3               // var4 <- var3
| id_tRNA_SLVcst, 9, 1              // var9 <- 1
| id_tRNA_IF0, 9
| | id_tRNA_OPELVcst, 0, 4, 7       // var4+=7
| | id_tRNA_RGLVLV, 5, 4            // var5 <- body val at var4
| | id_tRNA_CMPLVcst, 0, 5, instruction::MARKER, 6    // var6 <- var5==MARKER
| | id_tRNA_IF0, 6
| | | id_tRNA_OPELVcst, 0, 4, 2       // var4+=2
| | | id_tRNA_RGLVLV, 5, 4            // var5 <- body val at var4
| | | id_tRNA_CMPLVcst, 0, 5, -1, 9   // var9 <- var5==-1
| | | id_tRNA_INCLV, 1, 9             // var9--
| | | id_tRNA_OPELVcst, 1, 4, 2       // var4-=2
| | id_tRNA_SIJ
| | id_tRNA_SEJ
| id_tRNA_SWJ
| id_tRNA_OPELVcst, 0, 4, 6         // var4+=6 (end of DNA end marker)
|
| id_tRNA_SLVLV, 8, 4               // var8 <- var4
| id_tRNA_OPELVLV, 1, 8, 3          // var8-=var3 (var8 = DNA size)
| id_tRNA_INCLV, 0, 8               // var8++ (fencepost)
| 
| *var3 and var4 are DNA begin and end, var8 is DNA size*
|
|
| *output size = transcribed code + DNA + some metadata*
| *init metadata at beginning of new individual*
| id_tRNA_OPELVcst, 0, 7, 21        // var7+=21 : 3 molecules + ID
| id_tRNA_OPELVLV, 0, 7, 8          // var7+=var8 : DNA size
| id_tRNA_SOSLV, 7                  // output size = var 7
|
| id_tRNA_SLVcst, 6, 0              // var6 <- 0
| id_tRNA_SLVcst, 5, GGENESIS_ID
| id_tRNA_GLVO, 6, 5                // output[var6] <- var5 (genesis marker)
| id_tRNA_OPELVcst, 0, 6, 2         // var6+=2
| id_tRNA_SLVcst, 5, 3
| id_tRNA_GLVO, 6, 5                // output[var6] <- var5 (3)
| id_tRNA_INCLV, 0, 6               // var6++
| id_tRNA_GLVO, 6, 7                // output[var6] <- var7 (body size)
| id_tRNA_INCLV, 0, 6               // var6++
| id_tRNA_SLVcst, 5, 150
| id_tRNA_GLVO, 6, 5                // output[var6] <- var5 (stack pos)
| id_tRNA_INCLV, 0, 6               // var6++
| id_tRNA_SLVcst, 5, -1
| id_tRNA_GLVO, 6, 5                // output[var6] <- var5 (-1)
| *initial jmp*
| id_tRNA_OPELVcst, 0, 6, 3         // var6+=3
| id_tRNA_SLVcst, 5, 19
| id_tRNA_GLVO, 6, 5                // output[var6] <- var5 (JMP)
| id_tRNA_OPELVcst, 0, 6, 4         // var6+=4
| id_tRNA_SLVcst, 5, 36
| id_tRNA_GLVO, 6, 5                // output[var6] <- var5 (main pos : 36)
| id_tRNA_OPELVcst, 0, 6, 3         // var6+=3
|
| id_tRNA_OPELVLV, 1, 7, 8          // var7-=var8 : DNA size
| id_tRNA_OPELVcst, 1, 7, 21        // var7-=21
|
| *var6 is pos to cpy in output*
|
| *copy transcribed code*
|
| id_tRNA_SLVLV, 7, 1               // var7 <- var1 (begin of transcription ptr)
| id_tRNA_CMPLVLV, 0, 7, 2, 5       // var5 = var7 == var2 (end of transcription)
| id_tRNA_INCLV, 1, 5               // var5--
|
| id_tRNA_IF0, 5                    // if var5
| | id_tRNA_SLVDLV, 5, 7            // var5 <- *var7
| | id_tRNA_GLVO, 6, 5              // output[var6] <- var5
| | id_tRNA_INCLV, 0, 7             // var7++
| | id_tRNA_INCLV, 0, 6             // var6++
| | id_tRNA_CMPLVLV, 0, 7, 2, 5     // var5  = var7 == var2 (end of transcription)
| | id_tRNA_INCLV, 1, 5             // var5--
| id_tRNA_SWJ
|
| *copy DNA*
|
| id_tRNA_SLVLV, 7, 3               // var7 <- var3 (begin of DNA ptr)
| id_tRNA_CMPLVLV, 0, 7, 4, 5       // var5 = var7 == var4 (end of DNA)
| id_tRNA_INCLV, 1, 5               // var5--
|
| id_tRNA_IF0, 5                    // if var5
| | id_tRNA_RGLVLV, 5, 7            // var5 <- genes at var7
| | id_tRNA_GLVO, 6, 5              // output[var6] <- var5
| | id_tRNA_INCLV, 0, 7             // var7++
| | id_tRNA_INCLV, 0, 6             // var6++
| | id_tRNA_CMPLVLV, 0, 7, 4, 5     // var5  = var7 == var4 (end of DNA)
| | id_tRNA_INCLV, 1, 5             // var5--
| id_tRNA_SWJ
| id_tRNA_INCLV, 0, 6               // var6++
|
| *end of body*
| id_tRNA_SLVcst, 5, 46
| id_tRNA_GLVO, 6, 5                // output[var 6] <- var5 (final genetic marker)
| id_tRNA_INCLV, 0, 6               // var6++
| id_tRNA_SLVcst, 5, -1
| id_tRNA_GLVO, 6, 5                // output[var 6] <- var5 (-1)
|
| id_tRNA_WRITE, 9, 10            // write output at var10 (res in var9, useless)
| id_tRNA_INCS, 1                 // func ID list size = -1
| id_tRNA_RET
id_tRNA_SEJ

id_tRNA_RET
```


## Teleonomical code

### XASM code

```{XASM class.source='foldable'}
instruction::MARKER, 0, 105, 0, 0, 0, 0,


instruction::ADD, 1, 1, 0, 99, 99, 2,
instruction::CPY, 1, 2, 0, 100, 99, 0,
instruction::INC, 1, 0, 0, 99, 0, 0,
instruction::CPY, 1, 2, 0, 101, 99, 0,
instruction::INC, 1, 0, 0, 99, 0, 0,
instruction::CPY, 1, 2, 0, 102, 99, 0,


instruction::JRE, 0, 1, 0, 74, 102, 0,
instruction::CPY, 1, 1, 0, 103, 99, 0,
instruction::ADD, 1, 1, 1, 102, 102, 103,
instruction::CPY, 1, 2, 0, 104, 102, 0,
instruction::INC, 1, 0, 0, 102, 0, 0,
instruction::CPY, 2, 1, 0, 101, 103, 0,
instruction::CPY, 1, 1, 0, 99, 101, 0,
instruction::INC, 1, 0, 0, 99, 0, 0,
instruction::CPY, 2, 1, 0, 99, 104, 0,
instruction::INC, 1, 0, 0, 99, 0, 0,
instruction::CPY, 2, 1, 0, 99, 104, 0,

instruction::CALL, 0, 0, 0, 0, 207, 0,
instruction::CALL, 0, 0, 0, 0, 206, 0,

instruction::CPY, 1, 2, 0, 102, 99, 0,
instruction::DEC, 1, 0, 0, 99, 0, 0,
instruction::CPY, 1, 2, 0, 103, 99,
instruction::ADD, 1, 1, 0, 99, 99, 3,
instruction::CPY, 1, 2, 0, 101, 99, 0,
instruction::INC, 1, 0, 0, 101, 0, 0,
instruction::CPY, 1, 1, 0, 99, 103, 0,
instruction::DEC, 2, 0, 0, 99, 0, 0,
instruction::DEC, 1, 0, 0, 99, 0, 0,
instruction::DEC, 2, 0, 0, 99, 0, 0,

instruction::CPY, 1, 2, 0, 100, 99, 0,
instruction::CPY, 2, 0, 0, 100, 46, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 0, 0, 100, 0, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 1, 0, 100, 102, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 0, 0, 100, 0, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 0, 0, 100, 0, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 0, 0, 100, 0, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 0, 0, 100, 0, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,


instruction::CPY, 1, 1, 0, 104, 100, 0,
instruction::ADD, 1, 1, 0, 104, 104, 5,
instruction::JRE, 0, 1, 1, 3, 104, 101,
instruction::CPY, 1, 0, 0, 105, 0, 0,
instruction::JRA, 0, 0, 0, 2, 0, 0,
instruction::CPY, 1, 0, 0, 105, 1, 0,
instruction::DEC, 1, 0, 0, 105, 0, 0,
instruction::JRE, 0, 1, 0, 10, 105, 0,
instruction::CPY, 2, 2, 0, 100, 104, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::INC, 1, 0, 0, 104, 0, 0,
instruction::JRE, 0, 1, 1, 3, 104, 101,
instruction::CPY, 1, 0, 0, 105, 0, 0,
instruction::JRA, 0, 0, 0, 2, 0, 0,
instruction::CPY, 1, 0, 0, 105, 1, 0,
instruction::DEC, 1, 0, 0, 105, 0, 0,
instruction::JRS, 0, 0, 0, 9, 0, 0,

instruction::CPY, 2, 0, 0, 100, 46, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 0, 0, 100, 0, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 1, 0, 100, 102, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 0, 0, 100, 0, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 0, 0, 100, 0, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 0, 0, 100, 0, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 0, 0, 100, 0, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 0, 0, 100, 0, 0,
instruction::INC, 1, 0, 0, 100, 0, 0,
instruction::CPY, 2, 1, 0, 99, 100, 0,
instruction::SUB, 1, 1, 0, 99, 99, 3,
instruction::JRA, 0, 0, 0, 28, 0, 0,


instruction::DEC, 1, 0, 0, 99, 0, 0,
instruction::CPY, 1, 2, 0, 101, 99, 0,
instruction::CPY, 1, 2, 0, 105, 99, 0,
instruction::DEC, 1, 0, 0, 99, 0, 0,
instruction::CPY, 1, 2, 0, 100, 99, 0,
instruction::DEC, 1, 0, 0, 100, 0, 0,
instruction::DEC, 1, 0, 0, 101, 0, 0,
instruction::SUB, 1, 1, 1, 105, 105, 100,
instruction::SETOS, 1, 0, 0, 105, 0, 0,
instruction::CPY, 1, 1, 0, 105, 100, 0,
instruction::JRE, 0, 1, 1, 3, 105, 101,
instruction::CPY, 1, 0, 0, 106, 0, 0,
instruction::JRA, 0, 0, 0, 2, 0, 0,
instruction::CPY, 1, 0, 0, 106, 1, 0,
instruction::DEC, 1, 0, 0, 106, 0, 0,
instruction::CPY, 1, 0, 0, 107, 0, 0,

instruction::JRE, 0, 1, 0, 11, 106, 0,
instruction::CPY, 1, 2, 0, 106, 105, 0,
instruction::CPYOUT, 2, 1, 0, 107, 106, 0,
instruction::INC, 1, 0, 0, 105, 0, 0,
instruction::INC, 1, 0, 0, 107, 0, 0,
instruction::JRE, 0, 1, 1, 3, 105, 101,
instruction::CPY, 1, 0, 0, 106, 0, 0,
instruction::JRA, 0, 0, 0, 2, 0, 0,
instruction::CPY, 1, 0, 0, 106, 1, 0,
instruction::DEC, 1, 0, 0, 106, 0, 0,
instruction::JRS, 0, 0, 0, 10, 0, 0,


instruction::JMP, 2, 0, 0, 0, 0, 0,

instruction::MARKER, 0, 105, 0, 0, 0, 0,
```

### Raw code

```{Raw class.source='foldable'}
46, 0, 105, 0, 0, 0, 0,
7, 1, 1, 0, 99, 99, 2,
2, 1, 2, 0, 100, 99, 0,
5, 1, 0, 0, 99, 0, 0,
2, 1, 2, 0, 101, 99, 0,
5, 1, 0, 0, 99, 0, 0,
2, 1, 2, 0, 102, 99, 0,
27, 0, 1, 0, 74, 102, 0,
2, 1, 1, 0, 103, 99, 0,
7, 1, 1, 1, 102, 102, 103,
2, 1, 2, 0, 104, 102, 0,
5, 1, 0, 0, 102, 0, 0,
2, 2, 1, 0, 101, 103, 0,
2, 1, 1, 0, 99, 101, 0,
5, 1, 0, 0, 99, 0, 0,
2, 2, 1, 0, 99, 104, 0,
5, 1, 0, 0, 99, 0, 0,
2, 2, 1, 0, 99, 104, 0,
49, 0, 0, 0, 0, 207, 0,
49, 0, 0, 0, 0, 206, 0,
2, 1, 2, 0, 102, 99, 0,
6, 1, 0, 0, 99, 0, 0,
2, 1, 2, 0, 103, 99, 0,
7, 1, 1, 0, 99, 99, 3,
2, 1, 2, 0, 101, 99, 0,
5, 1, 0, 0, 101, 0, 0,
2, 1, 1, 0, 99, 103, 0,
6, 2, 0, 0, 99, 0, 0,
6, 1, 0, 0, 99, 0, 0,
6, 2, 0, 0, 99, 0, 0,
2, 1, 2, 0, 100, 99, 0,
2, 2, 0, 0, 100, 46, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 0, 0, 100, 0, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 1, 0, 100, 102, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 0, 0, 100, 0, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 0, 0, 100, 0, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 0, 0, 100, 0, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 0, 0, 100, 0, 0,
5, 1, 0, 0, 100, 0, 0,
2, 1, 1, 0, 104, 100, 0,
7, 1, 1, 0, 104, 104, 5,
27, 0, 1, 1, 3, 104, 101,
2, 1, 0, 0, 105, 0, 0,
20, 0, 0, 0, 2, 0, 0,
2, 1, 0, 0, 105, 1, 0,
6, 1, 0, 0, 105, 0, 0,
27, 0, 1, 0, 10, 105, 0,
2, 2, 2, 0, 100, 104, 0,
5, 1, 0, 0, 100, 0, 0,
5, 1, 0, 0, 104, 0, 0,
27, 0, 1, 1, 3, 104, 101,
2, 1, 0, 0, 105, 0, 0,
20, 0, 0, 0, 2, 0, 0,
2, 1, 0, 0, 105, 1, 0,
6, 1, 0, 0, 105, 0, 0,
21, 0, 0, 0, 9, 0, 0,
2, 2, 0, 0, 100, 46, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 0, 0, 100, 0, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 1, 0, 100, 102, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 0, 0, 100, 0, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 0, 0, 100, 0, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 0, 0, 100, 0, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 0, 0, 100, 0, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 0, 0, 100, 0, 0,
5, 1, 0, 0, 100, 0, 0,
2, 2, 1, 0, 99, 100, 0,
8, 1, 1, 0, 99, 99, 3,
20, 0, 0, 0, 28, 0, 0,
6, 1, 0, 0, 99, 0, 0,
2, 1, 2, 0, 101, 99, 0,
2, 1, 2, 0, 105, 99, 0,
6, 1, 0, 0, 99, 0, 0,
2, 1, 2, 0, 100, 99, 0,
6, 1, 0, 0, 100, 0, 0,
6, 1, 0, 0, 101, 0, 0,
8, 1, 1, 1, 105, 105, 100,
13, 1, 0, 0, 105, 0, 0,
2, 1, 1, 0, 105, 100, 0,
27, 0, 1, 1, 3, 105, 101,
2, 1, 0, 0, 106, 0, 0,
20, 0, 0, 0, 2, 0, 0,
2, 1, 0, 0, 106, 1, 0,
6, 1, 0, 0, 106, 0, 0,
2, 1, 0, 0, 107, 0, 0,
27, 0, 1, 0, 11, 106, 0,
2, 1, 2, 0, 106, 105, 0,
4, 2, 1, 0, 107, 106, 0,
5, 1, 0, 0, 105, 0, 0,
5, 1, 0, 0, 107, 0, 0,
27, 0, 1, 1, 3, 105, 101,
2, 1, 0, 0, 106, 0, 0,
20, 0, 0, 0, 2, 0, 0,
2, 1, 0, 0, 106, 1, 0,
6, 1, 0, 0, 106, 0, 0,
21, 0, 0, 0, 10, 0, 0,
19, 2, 0, 0, 0, 0, 0,
46, 0, 105, 0, 0, 0, 0,
```